management:
  endpoints:
    web:
      exposure:
        include: info,env,health,prometheus,startup
  endpoint:
    health:
      probes.enabled: true
      show-details: always # shows details about the health of each component when calling /actuator/health
      group:
        liveness.include: livenessState
        readiness.include: readinessState
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
  info:
    git.mode: full
  server:
    address: 0.0.0.0
    port: 8081
    ssl:
      enabled: false
server:
  address: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
spring:
  application:
    name: floriangubler-ch
  main:
    banner-mode: off
  thymeleaf:
    cache: false