apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.appName }}-certificate
spec:
  dnsNames:
    - "floriangubler.ch"
    - "*.floriangubler-ch"
  secretName: {{ .Values.appName }}-certificate
  privateKey:
    size: 2048
    rotationPolicy: Always
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: {{ .Values.appName }}-certificate-password
        key: password
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io