apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.appName }}-certificate
spec:
  isCA: false
  dnsNames:
    - "floriangubler.ch"
  secretName: {{ .Values.appName }}-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  keystore:
    pkcs12:
      create: true
      passwordSecretRef:
        name: {{ .Values.appName }}-certificate-password
        key: password
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io