apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 443
              protocol: TCP
              name: app
            - containerPort: 8081
              protocol: TCP
              name: management
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.config.javaToolOptions }}
            - name: KEYSTORE_LOCATION
              value: 'file:/var/run/secrets/java.io/keystores/keystore.p12'
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-cert-pass
                  key: password
          volumeMounts:
            - mountPath: /var/run/secrets/java.io/keystores
              name: volume-keystore
            - mountPath: /deployments/config
              name: volume-config
              readOnly: true
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /actuator/startup
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: volume-keystore
          secret:
            defaultMode: 420
            secretName: {{ .Values.appName }}-certificate
            items:
            - key: keystore.p12
              path: keystore.p12
        - name: volume-config
          projected:
            sources:
              - configMap:
                name: {{ .Values.appName }}-config-app
      imagePullSecrets:
        - name: docker-auth