apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: production
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443