apiVersion: v1
data:
  application.yml: |-
    server:
      port: 443
      ssl:
        enabled: true
        key-store-type: PKCS12
        key-store: ${KEYSTORE_LOCATION}
        key-store-password: ${KEYSTORE_PASSWORD}
        protocol: TLS
        enabled-protocols: TLSv1.2, TLSv1.3
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}-config-app